source ~/.vim/functions.vim

"##########################################################################

call plug#begin('~/.vim/bundle')

Plug 'junegunn/fzf'
Plug 'SirVer/ultisnips'
Plug 'dsiroky/vim-angry'
Plug 'caio/querycommandcomplete.vim'
Plug 'dcharbon/vim-flatbuffers',  { 'commit':'ecd75c33576d982f3c83545dff7b3c9245285e75' }
Plug 'derekwyatt/vim-fswitch'
Plug 'easymotion/vim-easymotion'
Plug 'junegunn/fzf.vim'
Plug 'majutsushi/tagbar'
Plug 'sjl/gundo.vim'
Plug 'tomtom/tcomment_vim'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'wsdjeg/vim-fetch'
Plug 'xolox/vim-misc'
Plug 'xolox/vim-session'
Plug 'yssl/QFEnter'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'gcmt/taboo.vim'
Plug 'dsiroky/vim-indentdetective'
Plug 'shumphrey/fugitive-gitlab.vim'
Plug 'sbdchd/neoformat'

Plug '~/.vim/bundle_handmade/cpp'
Plug '~/.vim/bundle_handmade/vim-todotxt'

call plug#end()

packadd termdebug

"##########################################################################

syntax on
color mujdefault

" higlight trailing whitespaces
match ExtraWhitespace /\s\+$/
autocmd WinEnter * match ExtraWhitespace /\s\+$/

"##########################################################################

source ~/.vim/keymaps.vim
source ~/.vim/commands.vim
source ~/.vim/abbreviations.vim

"##########################################################################

let g:UltiSnipsSnippetDirectories=["snippets_my", "snippets_default"]
let g:UltiSnipsSnippetsDir="~/.vim/my_snippets"
let g:UltiSnipsListSnippets="<plug>" " just a dummy key binding to turn it off

" ordinary regexes, not vim's
let g:regex_ignore_separate=['~$', '\.bak$', '\.sw[po]$',
                    \ '\.o$', '\.os$', '\.gch$',
                    \ '\.obj$', '\.sobj$', '\.exe$', '\.dll$', '\.pdb$', '\.ilk$',
                    \ '\.py[cow]$',
                    \ '\.png$', '\.gif$', '\.jpe?g$', '\.icon?$', '\.svg$',
                    \ '__pycache__$', '\.sconsign']

let g:regex_ignore=join(g:regex_ignore_separate, '|')

let g:netrw_menu = 1
let g:netrw_liststyle = 0
let g:netrw_fastbrowse = 0
let g:netrw_hide = 1
let g:netrw_list_hide = join(g:regex_ignore_separate, ',')
" turn it to vim's regex
let g:netrw_list_hide = substitute(g:netrw_list_hide, '\(\~|\?\)', '\\\1', 'g')
let g:netrw_sort_sequence = "[\/]$,*"
let g:netrw_mousemaps = 0
let g:netrw_banner = 0

let g:fzf_command_prefix = 'Fzf'
let g:fzf_buffers_jump = 0
let g:fzf_layout = { 'down':'~40%', }
let g:fzf_colors = {
  \ 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Special'],
  \ 'fg+':     ['fg', 'Normal'],
  \ 'bg+':     ['bg', 'Visual'],
  \ 'hl+':     ['fg', 'Special'],
  \ 'info':    ['fg', 'Comment'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'LineNr'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'NonText']
  \ }
let $FZF_DEFAULT_COMMAND = 'ag --hidden -l -g "" | grep -v ".git/"'
let $FZF_DEFAULT_OPTS = '--layout=reverse'

let g:tagbar_left = 1
let g:tagbar_autofocus = 1
let g:tagbar_autoclose = 1
let g:tagbar_sort = 0
let g:tagbar_indent = 2
let g:tagbar_show_visibility = 0
let g:tagbar_width = 70
let g:tagbar_show_linenumbers = -1

let g:session_autoload = 'no'
let g:session_autosave = 'yes'
set sessionoptions=blank,buffers,curdir,folds,winsize,tabpages

let g:gundo_prefer_python3 = 1

let g:EasyMotion_keys = 'asdfghjklqwertyuiopzxcvbnm'

let g:fugitive_gitlab_domains = ['https://gitlab.lastminute.com']

"let g:neoformat_verbose = 1
let g:neoformat_only_msg_on_error = 1
let g:neoformat_enabled_c = ['clangformat']
let g:neoformat_enabled_cpp = ['clangformat']
let g:neoformat_python_autopep8 = {
    \ 'exe': 'autopep8',
    \ 'args': ['--experimental', '-'],
    \ 'stdin': 1
    \ }
let g:neoformat_enabled_python = ['autopep8']
let g:neoformat_openscad_clangformat = {
            \ 'exe': 'clang-format',
            \ 'args': ['-assume-filename=' . expand('"%"')],
            \ 'stdin': 1,
            \ }
let g:neoformat_enabled_openscad = ['clangformat']

let g:surround_indent = 0

set modeline
set swapfile
set directory=~/.vim/tmp
set nobackup
set writebackup
set backupdir=~/.vim/tmp
set backupcopy=auto
set autoindent
set nosmartindent
set cinoptions=N-s
set backspace=2
set virtualedit=""
set whichwrap=b,s,<,>,h,l,[,]
set selection=inclusive
set foldmethod=manual
set nostartofline
set hidden
set completeopt=longest,menu
set complete=.,w,b,t
set sidescroll=1
set sidescrolloff=5
set gdefault
set pastetoggle=<F5>
set nonumber
set norelativenumber
set noruler
set shortmess=atToOI
set textwidth=0
set showcmd
set showmatch
set colorcolumn=101
set clipboard=unnamedplus
set mouse=
set ignorecase
set smartcase
set incsearch
set nohlsearch
set lazyredraw
set wildmode=longest:full,full
set wildmenu
set history=500
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<,nbsp:*,conceal:x
set diffopt=internal,filler,algorithm:patience,indent-heuristic
" do not autoinsert comment start
set formatoptions-=ro
" avoid autolinebreak
set formatoptions-=t
set matchpairs+=<:>
set signcolumn=yes
set nojoinspaces

set wrap
set linebreak
set breakindent
set showbreak=\ \ \ \ \ •••

set expandtab
set tabstop=4
set shiftwidth=0
set softtabstop=-1

" this prevents 'press enter' blocking message in many cases
"set cmdheight=2
set laststatus=2
set statusline=
set statusline+=%3*%y%r%*              "file type, readonly flag
set statusline+=%4*\ %<%{StatusLineFilename()}%*            "file path
set statusline+=%5*%m%*                "modified flag
set statusline+=%1*%=\ \ %l%*          "current line
set statusline+=%2*/%L%*               "total lines
set statusline+=%1*:%v\ %*             "virtual column number

set makeprg=scons
set grepprg=/mujbin/vimgrep
set grepformat=%f:%l:%c:%m

if &diff
    set cursorline
endif

if has("gui_running") && !has('nvim')
  set toolbariconsize=tiny
endif

if has("gui_running") || exists('g:GuiLoaded')
  if !has('nvim')
    source ~/.vim/ginit.vim
  endif
else
  "if ($TERM == "st-256color") || ($TERM == "screen-256color")
  "  set termguicolors
  "endif
  if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>[6 q\<Esc>\\"
    let &t_SR = "\<Esc>Ptmux;\<Esc>\<Esc>[4 q\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>[2 q\<Esc>\\"
  else
    let &t_SI = "\<Esc>[6 q"
    let &t_SR = "\<Esc>[4 q"
    let &t_EI = "\<Esc>[2 q"
  endif

  " faster modes switching
  set timeoutlen=1000 ttimeoutlen=0
endif

filetype plugin on
filetype indent on

"##########################################################################

augroup moje
  au!

  au FileType c,cpp set comments=sO:*\ -,mO:*\ \ ,exO:*/,s1:/*,mb:*,ex:*/,bO:///,O://
  au BufNewFile,BufRead *.hx set syntax=haxe
  au BufNewFile,BufRead SConstruct set filetype=python
  au BufNewFile,BufRead SConscript* set filetype=python
  au BufWritePost ~/.vim/doc/* :helptags ~/.vim/doc

  " jump to the last position when reopening a file
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$")
                        \ && &filetype != "gitcommit"
                        \ && &filetype != "gitrebase"
                        \ | exe "normal! g'\"" | endif

  au WinEnter * call Set_scrolloff()
  au BufReadPost * call Set_scrolloff()

  " non-gui VIM cursor distinguish normal/insert mode
  if !has('gui_running')
    au InsertEnter * set cursorline
    au InsertLeave * set nocursorline
  endif

  au BufEnter *.h let b:fswitchdst = 'c,cpp,cc'
  au BufEnter *.hpp let b:fswitchdst = 'cpp,cc'
  au BufEnter *.hxx let b:fswitchdst = 'cxx,cc'
  au BufEnter *.hh let b:fswitchdst = 'cc'
  au BufEnter *.h,*.hpp,*.hxx,*.hh let b:fswitchlocs = './,reg:/include/src/,reg:/include.*/src/,ifrel:|/include/|../src|'
  au BufEnter *.c let b:fswitchdst = 'h'
  au BufEnter *.cpp let b:fswitchdst = 'hpp,h'
  au BufEnter *.cxx let b:fswitchdst = 'hxx,h'
  au BufEnter *.cc let b:fswitchdst = 'h,hh'
  au BufEnter *.c,*.cpp,*.cxx,*.cc let b:fswitchlocs = './,reg:/src/include/,reg:|src|include/**|,ifrel:|/src/|../include|'

  au BufEnter *.h,*.hpp,*.hxx,*.hh,*.c,*.cpp,*.cxx,*.cc setlocal syntax=cpp.doxygen

  au FileType python setlocal equalprg=autopep8\ -aa\ -

  au BufNewFile *.html 0r ~/.vim/templates/tmplt.html
  au BufNewFile *.tex 0r ~/.vim/templates/tmplt.tex
  au BufNewFile *.h,*.hpp,*.hxx 0r ~/.vim/templates/tmplt.h

  au BufEnter * highlight CocFadeOut guibg=NONE guifg=NONE gui=NONE
augroup END
