# vim: set filetype=conf :

set -g status-style bg=colour8,fg=white
set -g status-left "[#S] "
set -g status-left-length 100
set -g status-right "#h"
setw -g window-status-current-style bg=colour239
setw -g window-status-format " #I:#W#F "
setw -g window-status-current-format " #I:#W#F "

set -g default-terminal "screen-256color"
# allow true color, fix tmux crash https://github.com/tmux/tmux/issues/1264
set -sa terminal-overrides ",st-*:Tc:Ss@"
set -g history-limit 100000
set -g history-file ~/.tmux_history
set -g mouse on
set -g allow-rename off
# 0 is too far ;-)
set -g base-index 1
setw -g pane-base-index 1
setw -g mode-keys vi
set -g destroy-unattached off
set -s escape-time 0
set -g display-panes-time 2000
set -g focus-events on
set -g pane-border-lines heavy

set-hook -g pane-mode-changed {
  if -F "#{pane_in_mode}" \
    "selectp -P bg=colour236" \
    "selectp -P default"
}

#--------------------------------------------------------------------------

set -g @jump-key 's'
run-shell ~/.tmux/tmux-jump/tmux-jump.tmux

#--------------------------------------------------------------------------

set -g prefix `
bind ` send-prefix
unbind C-b

bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind C new-window -c "~"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind J resize-pane -D 5
bind K resize-pane -U 5
bind H resize-pane -L 10
bind L resize-pane -R 10

bind -n M-Left  previous-window
bind -n M-Right next-window

yank="/mujbin/yank.sh"

bind -T copy-mode-vi / command-prompt -i -p "search down" "send -X search-forward-incremental \"%%%\""
bind -T copy-mode-vi ? command-prompt -i -p "search up" "send -X search-backward-incremental \"%%%\""
bind -n M-s copy-mode \; command-prompt -i -p "search up" "send -X search-backward-incremental \"%%%\""
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe "$yank"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear "$yank"
bind -n S-PPage copy-mode -eu
bind -T copy-mode-vi S-NPage send-keys -X page-down
bind -T copy-mode-vi C-b send-keys -X page-up
bind P command-prompt -p 'save history to filename:' -I '/tmp/tmux.scrollback' 'capture-pane -S - ; save-buffer %1 ; delete-buffer'
# there is a non-breakable space for "tagging" a previous prompt in a scrollback
bind B copy-mode -e \; send -X search-backward ': '

if-shell "test -f ~/.tmux.conf.local" "source ~/.tmux.conf.local"
